version: "3"

# Root Taskfile - delegates to example-specific Taskfiles
# Navigate to examples/node or examples/next and run `task` there

tasks:
  dev:node:
    desc: Start Node.js example development server
    dir: examples/node
    cmd: task dev

  dev:next:
    desc: Start Next.js example development server
    dir: examples/next
    cmd: task dev

  dev:form:
    desc: Start Form example development server
    dir: examples/form
    cmd: task dev

  default:
    desc: Show available examples
    cmds:
      - echo "Available examples:"
      - echo "  - examples/node    (cd examples/node && task --list)"
      - echo "  - examples/next    (cd examples/next && task --list)"
      - echo "  - examples/form    (cd examples/form && task --list)"
      - echo ""
      - echo "Quick start:"
      - echo "  - task dev:node    (start Node.js dev server)"
      - echo "  - task dev:next    (start Next.js dev server)"
      - echo "  - task dev:form    (start Form example dev server)"
