version: "3"

vars:
  DOTENVX: dotenvx run --

tasks:
  dev:
    desc: Start development server with auto-reload
    dir: be
    cmd: "pnpm run dev"

  start:
    desc: Run the application
    dir: be
    cmd: "pnpm run start"

  build:
    desc: Build TypeScript
    dir: be
    cmd: "tsc"

  test:
    desc: Run tests
    dir: be
    cmd: "vitest"

  test:ui:
    desc: Run tests with UI
    dir: be
    cmd: "vitest --ui"

  test:watch:
    desc: Run tests in watch mode
    dir: be
    cmd: "vitest --watch"

  db:generate:
    desc: Generate Drizzle migrations from schema
    dir: be
    cmd: "{{.DOTENVX}} drizzle-kit generate"

  db:migrate:
    desc: Run database migrations
    dir: be
    cmd: "{{.DOTENVX}} drizzle-kit migrate"

  db:push:
    desc: Push schema changes directly to database (dev only)
    dir: be
    cmd: "{{.DOTENVX}} drizzle-kit push"

  db:studio:
    desc: Launch Drizzle Studio
    dir: be
    cmd: "{{.DOTENVX}} drizzle-kit studio"

  db:drop:
    desc: Drop database tables
    cmd: "{{.DOTENVX}} drizzle-kit drop"
    prompt: This will drop all tables. Are you sure?

  install:
    desc: Install dependencies
    dir: be
    cmd: "pnpm install"

  clean:
    desc: Clean build artifacts and node_modules
    dir: be
    cmds:
      - rm -rf node_modules
      - rm -rf dist
      - rm -rf .turbo

  lint:
    desc: Lint code
    dir: be
    cmd: echo "Add your linter here (eslint, biome, etc.)"

  format:
    desc: Format code
    dir: be
    cmd: echo "Add your formatter here (prettier, biome, etc.)"

  default:
    desc: Show available tasks
    cmd: task --list
