version: "3"

vars:
  DOTENVX: dotenvx run --

tasks:
  dev:
    desc: Start development server with auto-reload
    cmd: "pnpm run dev"

  start:
    desc: Run the application
    cmd: "pnpm run start"

  build:
    desc: Build TypeScript
    cmd: "tsc"

  test:
    desc: Run tests
    cmd: "vitest"

  test:ui:
    desc: Run tests with UI
    cmd: "vitest --ui"

  test:watch:
    desc: Run tests in watch mode
    cmd: "vitest --watch"

  db:generate:
    desc: Generate Drizzle migrations from schema
    cmd: "pnpm run db:generate"

  db:migrate:
    desc: Run database migrations
    cmd: "pnpm run db:migrate"

  db:push:
    desc: Push schema changes directly to database (dev only)
    cmd: "pnpm run db:push"

  db:studio:
    desc: Launch Drizzle Studio
    cmd: "pnpm run db:studio"

  db:drop:
    desc: Drop database tables
    cmd: "pnpm run db:drop"
    prompt: This will drop all tables. Are you sure?

  install:
    desc: Install dependencies
    cmd: "pnpm install"

  clean:
    desc: Clean build artifacts and node_modules
    cmds:
      - rm -rf node_modules
      - rm -rf dist
      - rm -rf .turbo

  lint:
    desc: Lint code
    cmd: pnpm run lint || echo "No lint script found"

  format:
    desc: Format code
    cmd: pnpm run format || echo "No format script found"

  default:
    desc: Show available tasks
    cmd: task --list
