name: Notify Agent on Issue
on:
  issue_comment:
    types: [created]

jobs:
  trigger-agent:
    if: ${{ github.event.comment.body != 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Log issue details
        run: |
          echo "Triggered by issue #${{ github.event.issue.number }}"
          echo "Comment: ${{ github.event.comment.body }}"
          echo "Repository: ${{ github.repository }}"
          echo "Pull Request: ${{ github.event.issue.pull_request }}"

      - name: Call Agent Repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.AGENT_TRIGGER_TOKEN }}
          repository: quochuydev/x-agent
          event-type: generate-code
          client-payload: >-
            {
              "repo": "${{ github.repository }}",
              "comment": ${{ toJSON(github.event.comment.body) }},
              "user": "${{ github.event.comment.user.login }}",
              "issue_title": ${{ toJSON(github.event.issue.title) }},
              "issue_body": ${{ toJSON(github.event.issue.body) }},
              "issue_number": ${{ github.event.issue.number }},
              "pr_number": "${{ github.event.issue.number }}"
            }
